// <auto-generated />
using System;
using EuroTrans.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuroTrans.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104135754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("EuroTrans.Domain.Employees.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("license_number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auth0_user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shipment_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByEmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_by_employee_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByEmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_employee_id");

                    b.Property<float>("LocationLat")
                        .HasColumnType("REAL")
                        .HasColumnName("location_lat");

                    b.Property<float>("LocationLng")
                        .HasColumnType("REAL")
                        .HasColumnName("location_lng");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shipment_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivered_at");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("TEXT")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("EstimatedDeliveryDateUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("estimated_delivery_date");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tracking_id");

                    b.Property<Guid?>("TruckId")
                        .HasColumnType("TEXT")
                        .HasColumnName("truck_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TrackingId")
                        .IsUnique();

                    b.HasIndex("TruckId");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Trucks.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<float>("Capacity")
                        .HasColumnType("REAL")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("plate_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("trucks", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Employees.Driver", b =>
                {
                    b.HasOne("EuroTrans.Domain.Employees.Employee", "Employee")
                        .WithOne("Driver")
                        .HasForeignKey("EuroTrans.Domain.Employees.Driver", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Activity", b =>
                {
                    b.HasOne("EuroTrans.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuroTrans.Domain.Shipments.Shipment", null)
                        .WithMany("Activities")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Document", b =>
                {
                    b.HasOne("EuroTrans.Domain.Shipments.Shipment", null)
                        .WithMany("Documents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Milestone", b =>
                {
                    b.HasOne("EuroTrans.Domain.Shipments.Shipment", null)
                        .WithMany("Milestones")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Shipment", b =>
                {
                    b.HasOne("EuroTrans.Domain.Employees.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("EuroTrans.Domain.Trucks.Truck", null)
                        .WithMany()
                        .HasForeignKey("TruckId");

                    b.OwnsOne("EuroTrans.Domain.Shipments.ValueObjects.Address", "DestinationAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("destination_address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("destination_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("destination_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("destination_postal_code");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("EuroTrans.Domain.Shipments.ValueObjects.GeoLocation", "DestinationLocation", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("destination_lat");

                            b1.Property<float>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("destination_lng");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("EuroTrans.Domain.Shipments.ValueObjects.Address", "OriginAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressLine")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("origin_address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("origin_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("origin_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("origin_postal_code");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("EuroTrans.Domain.Shipments.ValueObjects.GeoLocation", "OriginLocation", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("origin_lat");

                            b1.Property<float>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("origin_lng");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("EuroTrans.Domain.Shipments.ValueObjects.Cargo", "Cargo", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("cargo_description");

                            b1.Property<float>("Volume")
                                .HasColumnType("REAL")
                                .HasColumnName("cargo_volume");

                            b1.Property<float>("Weight")
                                .HasColumnType("REAL")
                                .HasColumnName("cargo_weight");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("Cargo")
                        .IsRequired();

                    b.Navigation("DestinationAddress")
                        .IsRequired();

                    b.Navigation("DestinationLocation")
                        .IsRequired();

                    b.Navigation("OriginAddress")
                        .IsRequired();

                    b.Navigation("OriginLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("EuroTrans.Domain.Employees.Employee", b =>
                {
                    b.Navigation("Driver");
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Shipment", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Documents");

                    b.Navigation("Milestones");
                });
#pragma warning restore 612, 618
        }
    }
}
