// <auto-generated />
using System;
using EuroTrans.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuroTrans.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("EuroTrans.Domain.Activities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Drivers.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentShipmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentShipmentId")
                        .IsUnique();

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Milestones.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("LocationLat")
                        .HasColumnType("REAL");

                    b.Property<float>("LocationLng")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationPostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CargoDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("CargoVolume")
                        .HasColumnType("REAL");

                    b.Property<float>("CargoWeight")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentLocationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("DestinationLat")
                        .HasColumnType("REAL");

                    b.Property<float>("DestinationLng")
                        .HasColumnType("REAL");

                    b.Property<string>("DestinationPostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("OriginLat")
                        .HasColumnType("REAL");

                    b.Property<float>("OriginLng")
                        .HasColumnType("REAL");

                    b.Property<string>("OriginPostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofOfDeliveryUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TruckId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TrackingId")
                        .IsUnique();

                    b.HasIndex("TruckId");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Trucks.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("trucks", (string)null);
                });

            modelBuilder.Entity("EuroTrans.Domain.Activities.Activity", b =>
                {
                    b.HasOne("EuroTrans.Domain.Shipments.Shipment", "Shipment")
                        .WithMany("Activities")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuroTrans.Domain.Employees.Employee", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EuroTrans.Domain.Drivers.Driver", b =>
                {
                    b.HasOne("EuroTrans.Domain.Shipments.Shipment", "CurrentShipment")
                        .WithOne()
                        .HasForeignKey("EuroTrans.Domain.Drivers.Driver", "CurrentShipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EuroTrans.Domain.Employees.Employee", "Employee")
                        .WithOne("Driver")
                        .HasForeignKey("EuroTrans.Domain.Drivers.Driver", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentShipment");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EuroTrans.Domain.Milestones.Milestone", b =>
                {
                    b.HasOne("EuroTrans.Domain.Shipments.Shipment", "Shipment")
                        .WithMany("Milestones")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Shipment", b =>
                {
                    b.HasOne("EuroTrans.Domain.Drivers.Driver", "Driver")
                        .WithMany("Shipments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EuroTrans.Domain.Trucks.Truck", "Truck")
                        .WithMany("Shipments")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Driver");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("EuroTrans.Domain.Drivers.Driver", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("EuroTrans.Domain.Employees.Employee", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("EuroTrans.Domain.Shipments.Shipment", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("EuroTrans.Domain.Trucks.Truck", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
