name: Server CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore eurotrans.server/EuroTrans.sln

      - name: Build
        run: dotnet build eurotrans.server/EuroTrans.sln --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish eurotrans.server/src/EuroTrans.Api/EuroTrans.Api.csproj --configuration Release --output ./publish/api --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "euro-trans"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5EEA8F3C1C964300BE898AC8B6FEEA84 }}
          package: ./publish/api
